// app/layout.tsx
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

import { Header } from "@/components/header";
import { config } from "@/config";
import Web3ModalProvider from "@/context";
import { cn } from "@/lib/utils";
import { cookieToInitialState } from "wagmi";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Web3ModalProvider initialState={initialState}>
          <Header />
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
